// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: jai.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayHello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SayHello) Reset() {
	*x = SayHello{}
	mi := &file_jai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHello) ProtoMessage() {}

func (x *SayHello) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHello.ProtoReflect.Descriptor instead.
func (*SayHello) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{0}
}

type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Login) Reset() {
	*x = Login{}
	mi := &file_jai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{1}
}

type ListChats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListChats) Reset() {
	*x = ListChats{}
	mi := &file_jai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChats) ProtoMessage() {}

func (x *ListChats) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChats.ProtoReflect.Descriptor instead.
func (*ListChats) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{2}
}

type UploadJson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UploadJson) Reset() {
	*x = UploadJson{}
	mi := &file_jai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadJson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadJson) ProtoMessage() {}

func (x *UploadJson) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadJson.ProtoReflect.Descriptor instead.
func (*UploadJson) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{3}
}

type GetChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetChat) Reset() {
	*x = GetChat{}
	mi := &file_jai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChat) ProtoMessage() {}

func (x *GetChat) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChat.ProtoReflect.Descriptor instead.
func (*GetChat) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{4}
}

type AskJsonAI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AskJsonAI) Reset() {
	*x = AskJsonAI{}
	mi := &file_jai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskJsonAI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskJsonAI) ProtoMessage() {}

func (x *AskJsonAI) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskJsonAI.ProtoReflect.Descriptor instead.
func (*AskJsonAI) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{5}
}

type SayHello_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SayHello_Request) Reset() {
	*x = SayHello_Request{}
	mi := &file_jai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHello_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHello_Request) ProtoMessage() {}

func (x *SayHello_Request) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHello_Request.ProtoReflect.Descriptor instead.
func (*SayHello_Request) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SayHello_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SayHello_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SayHello_Response) Reset() {
	*x = SayHello_Response{}
	mi := &file_jai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHello_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHello_Response) ProtoMessage() {}

func (x *SayHello_Response) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHello_Response.ProtoReflect.Descriptor instead.
func (*SayHello_Response) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SayHello_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Login_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Pin   string `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
}

func (x *Login_Request) Reset() {
	*x = Login_Request{}
	mi := &file_jai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Login_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_Request) ProtoMessage() {}

func (x *Login_Request) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_Request.ProtoReflect.Descriptor instead.
func (*Login_Request) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Login_Request) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Login_Request) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type Login_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *Login_Response) Reset() {
	*x = Login_Response{}
	mi := &file_jai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Login_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_Response) ProtoMessage() {}

func (x *Login_Response) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_Response.ProtoReflect.Descriptor instead.
func (*Login_Response) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Login_Response) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ListChats_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *ListChats_Request) Reset() {
	*x = ListChats_Request{}
	mi := &file_jai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChats_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChats_Request) ProtoMessage() {}

func (x *ListChats_Request) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChats_Request.ProtoReflect.Descriptor instead.
func (*ListChats_Request) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ListChats_Request) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type ListChats_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chats []*Chat `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
}

func (x *ListChats_Response) Reset() {
	*x = ListChats_Response{}
	mi := &file_jai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChats_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChats_Response) ProtoMessage() {}

func (x *ListChats_Response) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChats_Response.ProtoReflect.Descriptor instead.
func (*ListChats_Response) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ListChats_Response) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type UploadJson_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	FileName string `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	JsonData string `protobuf:"bytes,3,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
}

func (x *UploadJson_Request) Reset() {
	*x = UploadJson_Request{}
	mi := &file_jai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadJson_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadJson_Request) ProtoMessage() {}

func (x *UploadJson_Request) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadJson_Request.ProtoReflect.Descriptor instead.
func (*UploadJson_Request) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{3, 0}
}

func (x *UploadJson_Request) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UploadJson_Request) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadJson_Request) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

type UploadJson_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chat *Chat `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
}

func (x *UploadJson_Response) Reset() {
	*x = UploadJson_Response{}
	mi := &file_jai_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadJson_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadJson_Response) ProtoMessage() {}

func (x *UploadJson_Response) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadJson_Response.ProtoReflect.Descriptor instead.
func (*UploadJson_Response) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{3, 1}
}

func (x *UploadJson_Response) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type GetChat_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ChatID string `protobuf:"bytes,2,opt,name=chatID,proto3" json:"chatID,omitempty"`
}

func (x *GetChat_Request) Reset() {
	*x = GetChat_Request{}
	mi := &file_jai_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChat_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChat_Request) ProtoMessage() {}

func (x *GetChat_Request) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChat_Request.ProtoReflect.Descriptor instead.
func (*GetChat_Request) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetChat_Request) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetChat_Request) GetChatID() string {
	if x != nil {
		return x.ChatID
	}
	return ""
}

type GetChat_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chat *Chat `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
}

func (x *GetChat_Response) Reset() {
	*x = GetChat_Response{}
	mi := &file_jai_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChat_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChat_Response) ProtoMessage() {}

func (x *GetChat_Response) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChat_Response.ProtoReflect.Descriptor instead.
func (*GetChat_Response) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetChat_Response) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type AskJsonAI_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ChatID   string `protobuf:"bytes,2,opt,name=chatID,proto3" json:"chatID,omitempty"`
	Question string `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
}

func (x *AskJsonAI_Request) Reset() {
	*x = AskJsonAI_Request{}
	mi := &file_jai_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskJsonAI_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskJsonAI_Request) ProtoMessage() {}

func (x *AskJsonAI_Request) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskJsonAI_Request.ProtoReflect.Descriptor instead.
func (*AskJsonAI_Request) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{5, 0}
}

func (x *AskJsonAI_Request) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *AskJsonAI_Request) GetChatID() string {
	if x != nil {
		return x.ChatID
	}
	return ""
}

func (x *AskJsonAI_Request) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type AskJsonAI_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Chat   *Chat  `protobuf:"bytes,2,opt,name=chat,proto3" json:"chat,omitempty"` // Full chat history
}

func (x *AskJsonAI_Response) Reset() {
	*x = AskJsonAI_Response{}
	mi := &file_jai_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskJsonAI_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskJsonAI_Response) ProtoMessage() {}

func (x *AskJsonAI_Response) ProtoReflect() protoreflect.Message {
	mi := &file_jai_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskJsonAI_Response.ProtoReflect.Descriptor instead.
func (*AskJsonAI_Response) Descriptor() ([]byte, []int) {
	return file_jai_proto_rawDescGZIP(), []int{5, 1}
}

func (x *AskJsonAI_Response) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AskJsonAI_Response) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

var File_jai_proto protoreflect.FileDescriptor

var file_jai_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6a, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0d, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x4f, 0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x1a, 0x1d, 0x0a, 0x07, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x24, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x67, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x1a, 0x31, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x6e, 0x1a, 0x2b, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x5d, 0x0a, 0x09, 0x4c, 0x69, 0x73,
	0x74, 0x43, 0x68, 0x61, 0x74, 0x73, 0x1a, 0x21, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x2d, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61,
	0x74, 0x52, 0x05, 0x63, 0x68, 0x61, 0x74, 0x73, 0x22, 0x94, 0x01, 0x0a, 0x0a, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x4a, 0x73, 0x6f, 0x6e, 0x1a, 0x59, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61,
	0x74, 0x61, 0x1a, 0x2b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x22,
	0x71, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x1a, 0x39, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x68, 0x61, 0x74, 0x49, 0x44, 0x1a, 0x2b, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x04, 0x63, 0x68,
	0x61, 0x74, 0x22, 0xa7, 0x01, 0x0a, 0x09, 0x41, 0x73, 0x6b, 0x4a, 0x73, 0x6f, 0x6e, 0x41, 0x49,
	0x1a, 0x55, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x43, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x04, 0x63,
	0x68, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x32, 0x82, 0x04, 0x0a,
	0x0d, 0x4a, 0x73, 0x6f, 0x6e, 0x41, 0x49, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b,
	0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x79, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1c, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x16, 0x3a, 0x01, 0x2a, 0x22, 0x11, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x2d,
	0x61, 0x69, 0x2f, 0x73, 0x61, 0x79, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x4f, 0x0a, 0x05, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x3a, 0x01, 0x2a, 0x22, 0x0e, 0x2f, 0x6a,
	0x73, 0x6f, 0x6e, 0x2d, 0x61, 0x69, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x66, 0x0a, 0x09,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x68, 0x61, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x12, 0x1c, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x2d, 0x61, 0x69,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x7d, 0x2f, 0x63,
	0x68, 0x61, 0x74, 0x73, 0x12, 0x68, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x12,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x68, 0x61, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x26, 0x12, 0x24, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x2d,
	0x61, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x7d,
	0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x7b, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44, 0x7d, 0x12, 0x71,
	0x0a, 0x09, 0x41, 0x73, 0x6b, 0x4a, 0x73, 0x6f, 0x6e, 0x41, 0x49, 0x12, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x73, 0x6b, 0x4a, 0x73, 0x6f, 0x6e, 0x41, 0x49, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x73,
	0x6b, 0x4a, 0x73, 0x6f, 0x6e, 0x41, 0x49, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x29, 0x3a, 0x01, 0x2a, 0x1a, 0x24, 0x2f, 0x6a, 0x73,
	0x6f, 0x6e, 0x2d, 0x61, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x7b, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x7d, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x2f, 0x7b, 0x63, 0x68, 0x61, 0x74, 0x49, 0x44,
	0x7d, 0x42, 0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x76, 0x69, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x61, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jai_proto_rawDescOnce sync.Once
	file_jai_proto_rawDescData = file_jai_proto_rawDesc
)

func file_jai_proto_rawDescGZIP() []byte {
	file_jai_proto_rawDescOnce.Do(func() {
		file_jai_proto_rawDescData = protoimpl.X.CompressGZIP(file_jai_proto_rawDescData)
	})
	return file_jai_proto_rawDescData
}

var file_jai_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_jai_proto_goTypes = []any{
	(*SayHello)(nil),            // 0: proto.SayHello
	(*Login)(nil),               // 1: proto.Login
	(*ListChats)(nil),           // 2: proto.ListChats
	(*UploadJson)(nil),          // 3: proto.UploadJson
	(*GetChat)(nil),             // 4: proto.GetChat
	(*AskJsonAI)(nil),           // 5: proto.AskJsonAI
	(*SayHello_Request)(nil),    // 6: proto.SayHello.Request
	(*SayHello_Response)(nil),   // 7: proto.SayHello.Response
	(*Login_Request)(nil),       // 8: proto.Login.Request
	(*Login_Response)(nil),      // 9: proto.Login.Response
	(*ListChats_Request)(nil),   // 10: proto.ListChats.Request
	(*ListChats_Response)(nil),  // 11: proto.ListChats.Response
	(*UploadJson_Request)(nil),  // 12: proto.UploadJson.Request
	(*UploadJson_Response)(nil), // 13: proto.UploadJson.Response
	(*GetChat_Request)(nil),     // 14: proto.GetChat.Request
	(*GetChat_Response)(nil),    // 15: proto.GetChat.Response
	(*AskJsonAI_Request)(nil),   // 16: proto.AskJsonAI.Request
	(*AskJsonAI_Response)(nil),  // 17: proto.AskJsonAI.Response
	(*User)(nil),                // 18: proto.User
	(*Chat)(nil),                // 19: proto.Chat
}
var file_jai_proto_depIdxs = []int32{
	18, // 0: proto.Login.Response.user:type_name -> proto.User
	19, // 1: proto.ListChats.Response.chats:type_name -> proto.Chat
	19, // 2: proto.UploadJson.Response.chat:type_name -> proto.Chat
	19, // 3: proto.GetChat.Response.chat:type_name -> proto.Chat
	19, // 4: proto.AskJsonAI.Response.chat:type_name -> proto.Chat
	6,  // 5: proto.JsonAIService.SayHello:input_type -> proto.SayHello.Request
	8,  // 6: proto.JsonAIService.Login:input_type -> proto.Login.Request
	10, // 7: proto.JsonAIService.ListChats:input_type -> proto.ListChats.Request
	14, // 8: proto.JsonAIService.GetChat:input_type -> proto.GetChat.Request
	16, // 9: proto.JsonAIService.AskJsonAI:input_type -> proto.AskJsonAI.Request
	7,  // 10: proto.JsonAIService.SayHello:output_type -> proto.SayHello.Response
	9,  // 11: proto.JsonAIService.Login:output_type -> proto.Login.Response
	11, // 12: proto.JsonAIService.ListChats:output_type -> proto.ListChats.Response
	15, // 13: proto.JsonAIService.GetChat:output_type -> proto.GetChat.Response
	17, // 14: proto.JsonAIService.AskJsonAI:output_type -> proto.AskJsonAI.Response
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_jai_proto_init() }
func file_jai_proto_init() {
	if File_jai_proto != nil {
		return
	}
	file_objects_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jai_proto_goTypes,
		DependencyIndexes: file_jai_proto_depIdxs,
		MessageInfos:      file_jai_proto_msgTypes,
	}.Build()
	File_jai_proto = out.File
	file_jai_proto_rawDesc = nil
	file_jai_proto_goTypes = nil
	file_jai_proto_depIdxs = nil
}
